### ISSUE TITLE
tensorrt_policy is missing

### ISSUE THREAD

**Issue by frankie4fingers** [shacklettbp/bps-nav#3]
resnet_policy.py contains the following code:
```
from tensorrt_policy import TensorRTPolicy
```
but it seems this package is missing. Please add it to repo.

**Comment by shacklettbp** [comment]
Sorry for the slow response. The tensorrt_policy package doesn't exist in this repo because limitations of TensorRT prevented us from realizing any performance gains by using it. Specifically, the TensorRT module needs to be updated on the CPU every time weights change, which is quite often in the RL setting. The overhead of these weight updates outweighs the speedup from TensorRT, which only can accelerate inference anyway (not the much more expensive backprop phase during PPO).
